theme: jekyll-theme-slate
title: Waybeams
description: fast, stable and delightful graphical user experiences
github:
  owner_name: Luke Bayes
  owner_url: http://lukebayes.com
  repository_name: Waybeams
  repository_url: https://github.com/waybeams/waybeams
