theme: jekyll-theme-slate
title: Waybeams
description: Fast, Stable and Delightful UI
github:
  owner_name: Luke Bayes
  owner_url: http://lukebayes.com
  repository_name: Waybeams
  repository_url: https://github.com/waybeams/waybeams
